name: pledgemircbot
version: 0.1.1
description: An IRC bot.
author: Alexander Haslam theperson@alexhaslam.me
homepage: https://pledgem.com
environment:
  sdk: '>=1.8.0 <2.0.0'
dependencies:
  irc: ">=2.0.1 <3.0.0"
dev_dependencies:
  unittest: any
